import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import MainBody from "@/components/MainBody";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gamemano",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex h-screen">
          <MainBody>{children}</MainBody>
        </div>
      </body>
    </html>
  );
}
